public without sharing class AccountTriggerHandler implements TriggerInterface {
    public void beforeInsert(List<Account> lstAccounts) {
        
    }
    public void afterInsert(Map<Id, Account> mapNewAccounts) {

    }
    public void beforeUpdate(Map<Id, sObject> mapOldAccounts, Map<Id, sObject> mapNewAccounts) {

    }
    public void afterUpdate(Map<Id, sObject> mapOldAccounts, Map<Id, sObject> mapNewAccounts) {

    }
    public void beforeDelete(Map<Id, sObject> mapOldAccounts) {

    }
    public void afterDelete(Map<Id, sObject> mapOldAccounts) {

    }
    public void afterUndelete(Map<Id, sObject> mapNewAccounts) {

    }
}